# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Prob 140'
tagline:          'Prob 140'
description:      'Probability for Data Science <br /> Ani Adhikari <br />'
url:              http://probability.gitlab.io
baseurl:          /sp17/

author:
  name:           'Dibya Ghosh, Jason Zhang'
  url:            http://prob140.org

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
